### ISSUE TITLE
knimin/handlers/access_control.py confusion between users

### ISSUE THREAD

**Issue by sjanssen2** [biocore/labadmin#125]
I think there is a logical error in the post method regarding the user that makes the edit and the user that should be edited.
`        if [7, 'Admin'] not in user_levels:
            self.redirect('/logged_in_index/')
        else:
`
where, `user_levels` is the access levels of the user that shall be edited. I think it should be the access level of the logged in user that want to make the edit.

**Comment by wasade** [comment]
I believe it is operating as you expect, where `user_levels` corresponds to the logged in user. See [here](https://github.com/biocore/labadmin/blob/master/knimin/handlers/access_control.py#L28) and [here](https://github.com/biocore/labadmin/blob/master/knimin/handlers/access_control.py#L35), although I am a bit confused about the [`alter_access`](https://github.com/biocore/labadmin/blob/master/knimin/handlers/access_control.py#L30) call

**Comment by sjanssen2** [comment]
but [here](https://github.com/biocore/labadmin/blob/master/knimin/handlers/access_control.py#L28) is fetching the 'user' argument sent by POST. It is not grabbing the credentials of the user logged in to the system. That would be BaseHandler.get_current_user()

**Comment by wasade** [comment]
it's [implicit](https://github.com/biocore/labadmin/blob/master/knimin/handlers/access_control.py#L9) i think. my earlier comment was wrong, but i believe the code is correct although confusing

**Comment by sjanssen2** [comment]
I changed the code, such that we now only relay on the class decorator `@set_access(['Admin'])` which should be fine. We can close this issue, when PR #128 gets merged.
