### ISSUE TITLE
Populate test database

### ISSUE THREAD

**Issue by sjanssen2** [biocore/labadmin#169]
Issues to resolve before we can move to the new DB version from american-gut-web:
- [x] 11 labadmin/knimin/lib/tests/test_data_access.py @sjanssen2
- [x]  1 labadmin/knimin/tests/test_ag_add_barcode_kit.py @sjanssen2
- [x]  2 labadmin/knimin/tests/test_ag_new_barcode.py @sjanssen: I am failing and need help with this!
- [x]  2 labadmin/knimin/tests/test_ag_new_kit.py @josenavas (PR IN)
- [x]  1 labadmin/knimin/tests/test_ag_pulldown.py
- [x]  1 labadmin/knimin/tests/test_ag_search.py @sjanssen2
- [x]  1 labadmin/knimin/tests/test_ag_third_party.py @sjanssen2
- [x]  1 labadmin/knimin/tests/test_ag_update_geocode.py @josenavas PR :(https://github.com/biocore/labadmin/pull/180)
- [ ] 10 labadmin/knimin/tests/test_barcode_util.py @sjanssen2 https://github.com/biocore/labadmin/pull/178
- [x]  1 labadmin/knimin/tests/test_projects_summary.py @josenavas (PR IN)

**Comment by sjanssen2** [comment]
- [ ] labadmin test user needs to be set to 'test' not 'test@foo.bar'

**Comment by josenavas** [comment]
@sjanssen2 I noticed that it was set up to `test`. I actively change it to `test@foo.bar` because the user are emails, so I wanted to actually have an email on the test. Do you think that change is too much of a burden?

**Comment by sjanssen2** [comment]
Yes, because than I need to have some mechanism to first obtain the name 
of the test user as it will be different between current and new DB. Let 
us have 'test' for now and some time in the future we might want to make 
the transition to a more email like test user.

**Comment by josenavas** [comment]
Ok, will update the scrubbing script.

**Comment by josenavas** [comment]
@sjanssen2 can you put your name next to the files that you are working on, if any? This way we don't overlap

**Comment by sjanssen2** [comment]
@josenavas You introduced utf-8 chars to zip codes. I now see that our code is not compatible with utf-8 for zip codes :-( 
Can you please have a look at data_access.py function get_geocode_zipcode() and tell me how to escape "zipcode" when passed to self._con.execute(sql, ...)?
I have a really hard time to understand that right now.

**Comment by josenavas** [comment]
@sjanssen2 can you post some error message? The postgres DB should be configured to use utf-8 characters, so we shouldn't need to escape anything. Maybe the error message will help to identify the issue.

**Comment by sjanssen2** [comment]
I think I found the problem. PR is in.

**Comment by sjanssen2** [comment]
@wasade @josenavas Please have look at get_unassigned_barcodes() in data_access. The SQL statement 
sql = """SELECT DISTINCT barcode FROM barcodes.barcode
                 LEFT JOIN barcodes.project_barcode USING (barcode)
                 WHERE barcodes.project_barcode.barcode IS NULL
                 ORDER BY barcode ASC"""
times out for the new DB version. If I manually execute the statement from psql it returns after 0.2 sec. Thus, I figure something with the SQLHandler is wrong.

**Comment by wasade** [comment]
What value of `n` is being used?

**Comment by josenavas** [comment]
@sjanssen2 I tried to execute that function from ipython directly and it runs quite fast. I tried w/o values of n, passing 500, 1000 and 10000 (1000 and 10000 failed with a value error as expected). I think there may some kind of interaction in the tests that makes that test to fail. Can you send which is the failing test?

**Comment by josenavas** [comment]
I was using the scrubbed one

**Comment by wasade** [comment]
That's weird that scrubbing would change this behavior?

**Comment by sjanssen2** [comment]
I figure it is because of the sheer numbers, Jose's version is way more barcodes than v22

**Comment by wasade** [comment]
Is it slow on the production system where it's used via the UI?

**Comment by josenavas** [comment]
@sjanssen2 I will start working on test_ag_new_barcode.py. I saw your comment asking for help :)

**Comment by sjanssen2** [comment]
@josenavas to check if something else is left, just run nosetests with your scrubbed version and we will see where it fails

**Comment by sjanssen2** [comment]
Bad news, right now following tests fail on my machine:
- [ ] 1 labadmin/knimin/tests/test_ag_add_barcode_kit.py
- [ ] 2 labadmin/knimin/tests/test_ag_edit_barcode.py
- [ ] 2 labadmin/knimin/tests/test_ag_edit_participant.py
- [ ] 2 labadmin/knimin/tests/test_ag_new_barcode.py
- [ ] 2 labadmin/knimin/tests/test_ag_new_kit.py
- [ ] 1 labadmin/knimin/tests/test_ag_pulldown.py
- [ ] 1 labadmin/knimin/tests/test_barcode_util.py
- [ ] 1 labadmin/knimin/tests/test_projects_summary.py

**Comment by sjanssen2** [comment]
one of the email strings in the db have an ending whitespace: 'tNzXpOPHai@DqLWY.,! '
When passed around via get() and elf.get_argument('email', None) this whitespace is lost.
Any idea how to cope with that? @josenavas @antgonza @wasade

**Comment by josenavas** [comment]
spaces are not allowed on emails so probably that was an oversight when generating the scrubbed database.

**Comment by josenavas** [comment]
Apparently somebody had a space somewhere on their email (probably at the beginning of the string in the DB) and that's why it pop out in one of the random emails. it is also surprising the ',' and '!' characters.... Fixing on the scrub script.

**Comment by josenavas** [comment]
@sjanssen2 I've updated the scrubbed DB - it shouldn't include any of those characters on the emails.

**Comment by sjanssen2** [comment]
where can I get this update?

**Comment by josenavas** [comment]
On my [AG-web PR](https://github.com/biocore/american-gut-web/pull/645).

**Comment by sjanssen2** [comment]
I am out for the weekend now, would be wonderful if you could fix the last outstanding PRs :-)
