### ISSUE TITLE
American Gut Country handling

### ISSUE THREAD

**Issue by jwdebelius** [biocore/labadmin#17]
I was playing with the new round 1-21 data tonight (thanks @wasade, @EmbrietteH, @squirrelo). I noticed that some of the country representations were kind of weird.

I understand that Ireland is its own country. But, for our purposes, I think we should combine Ireland, Jersey, and the Isle of Man into the UK, and the provide another column that specifies some sort of smaller geographic region within Britain. I don't know enough about British Geography to specify what this region should be. Maybe the individual country (i.e. Ireland, Northern Ireland, Scotland, Wales, England), maybe something smaller.

Countries list and counts for all samples below:
```COUNTRY
Australia                159
Belgium                   87
Brazil                     1
Canada                    75
China                      3
Czech Republic             7
Denmark                    1
Finland                    1
France                     8
Germany                   11
India                      1
Ireland                    2
Isle of Man                1
Italy                      4
Japan                      3
Jersey                     1
Netherlands                6
New Zealand                5
None                      54
Norway                     5
Poland                     3
Puerto Rico                1
Spain                      4
Sweden                     2
Switzerland               12
Thailand                   9
USA                     6291
United Arab Emirates       1
United Kingdom           718
```

**Comment by rob-knight** [comment]
Do not combine Ireland with the U.K. (except Northern Ireland which is part
of the U.K.), we will get a lot of hate mail...

On Oct 27, 2015, at 9:17 PM, J W Debelius <notifications@github.com> wrote:

I was playing with the new round 1-21 data tonight (thanks @wasade
<https://github.com/wasade>, @EmbrietteH <https://github.com/EmbrietteH>,
@squirrelo <https://github.com/squirrelo>). I noticed that some of the
country representations were kind of weird.

I understand that Ireland is its own country. But, for our purposes, I
think we should combine Ireland, Jersey, and the Isle of Man into the UK,
and the provide another column that specifies some sort of smaller
geographic region within Britain. I don't know enough about British
Geography to specify what this region should be. Maybe the individual
country (i.e. Ireland, Northern Ireland, Scotland, Wales, England), maybe
something smaller.

Countries list and counts for all samples below:

Australia                159
Belgium                   87
Brazil                     1
Canada                    75
China                      3
Czech Republic             7
Denmark                    1
Finland                    1
France                     8
Germany                   11
India                      1
Ireland                    2
Isle of Man                1
Italy                      4
Japan                      3
Jersey                     1
Netherlands                6
New Zealand                5
None                      54
Norway                     5
Poland                     3
Puerto Rico                1
Spain                      4
Sweden                     2
Switzerland               12
Thailand                   9
USA                     6291
United Arab Emirates       1
United Kingdom           718

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/labadmin/issues/17>.

**Comment by EmbrietteH** [comment]
Closing (see Rob's comment).
