### ISSUE TITLE
geocoder

### ISSUE THREAD

**Issue by sjanssen2** [biocore/labadmin#196]
I often see in our unit tests, be it on my local machine or in Travis, that geocoder produces some timeouts. Daniel told me that he doesn't really trust this piece of code.

What about replacing our geocoder with this library: [http://geopy.readthedocs.io/en/latest/#](http://geopy.readthedocs.io/en/latest/#) ? 

We also use a complicated caching mechanism to save some lookups based on zip code. We currently have ~13000 participants in our DB and ~6000 entries in our cache table ag.zipcodes.
Is it really worth it?

**Comment by josenavas** [comment]
I'm happy to replace with an already existing library - less code that we have to maintain.
I think the cache was put in place because the Google Maps API have a limit on the number of queries that you can perform in a day, so I think it was done to avoid performing too many queries.

**Comment by wasade** [comment]
Yes and :+1:

**Comment by sjanssen2** [comment]
Yes, there is a limit on public google API calls. But I think we only need to geocode each "barcode" or "survey" once. Thus, the amount of calls is quite limited - I think. My main goal is to make our code base easier :-)

**Comment by sjanssen2** [comment]
If I understand our code correct, than the result of geocoder are latitude, longitude and elevation in table ag.ag_login. This table only gets edited (besides geocoding) from amgut if a new participant subscribes or from labadmin if we update participant information.

Therefore, I'd like to suggest to move the geocoding functionality to amgut and execute geocoding when a participant subscribes, i.e. amgut/handlers/auth_handler.py post method calls method addAGLogin from amgut/lib/data_access/ag_data_access.py
Furthermore, labadmin would import the geocoding module (to avoid code duplication and labadmin only works if amgut web exists) and does the geocoding for participant updates. 
In addition, we might also want to go over the full list of participant and check if lat/long/elev is present prior to a pulldown.

Would you agree with this approach?

**Comment by wasade** [comment]
Seems reasonable? iirc, we were also caching the geocoding bits in redis
too?

**Comment by sjanssen2** [comment]
I don't know how redis works. To me it seems to be rather transparent to our codebase. Would I find traces if the google API calls would go through redis server instead of directly to googles URL?

**Comment by wasade** [comment]
I dont actually know if we are caching in redis anymore. I thought we were
at one point but perhaps that changed. I cannot investigate the codebase
right now to assess this.

**Comment by wasade** [comment]
Geocoder replaced in #249
